## 返回值

通过返回值表示成功或失败. 可以使用特定错误码 `errno`, 或者规定一个正常值定义域之外的数字来标识错误. 不打断正常控制流, 因此必须显式检查.

```c
```

## 断言

检查失败立即终止程序. 适合开发阶段正确性测试, 在发布时利用编译手段禁用内部断言, 提高整体效率. 

```cpp
#include <cassert>

assert(b != 0);
```

## 异常

使用*异常 (Exceptions)* 会打断正常控制流, 将常规逻辑和错误处理逻辑分离. 常见设计错误是常规逻辑依赖于*异常*导致的控制流.

声明方法: 
```cpp
throw domain_error ("divided by zero");
```

常见异常: 
- `domain_error`: 定义在 `<stdexcept>`, 报告函数参数取值不可接受.


捕捉异常:
```cpp
try {
	/**/
}catch( some_error ){
	/* handle an exception*/
}
```

```cpp
class TracedException {
public:
    TracedException(
                std::string_view msg = {},
                std::stacktrace trc = std::stacktrace::current()) {
        if (!msg.empty()) {
            std::cerr << msg << '\n';
        }
        std::cerr << trc;
    }
};
 
void f() {
    // ...
    throw TracedException("Full stacktrace");
}
```

## 条件值

类似 Rust 的 Option 概念, 或者 Haskell 的 Maybe. 用 Option 包装一个返回值, 返回值可能正常, 也可能是错误的 (`nullopt`), 在语义上区分了正确与错误的返回值, 并且不打断控制流.

```cpp
#include <optional>

std::optional<int> parseSomething(const std::string& str) noexcept {
	size_t pos;
	int result = std::stoi(str, &pos); 
	if (pos == str.length())
		return result;
	return std::nullopt;
}

std::optional<int> opt = 1;

// 直接取值, 可能失败
*opt;

// 使用 value(), 无值则抛出异常
try {
	opt.value();
} catch (const std::bad_optional_access& e) { }

// 使用 value_or() 提供默认值
opt.value_or(0);

// 无异常判断方法:
if (opt.has_value()) 
	...

if (opt == std::nullopt)
	...
```